/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'entry1_type0x09.dylib'
*/
@import Darwin;
#include "ida_types.h"

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long


/* 160 */
enum CPUFamily : uint32_t
{
  CPUFamily_A8 = 0x2C91A47E,
  CPUFamily_A9 = 0x92FB37C8,
  CPUFamily_A10 = 0x67CEEE93,
  CPUFamily_A11 = 0xE81E7EF6,
  CPUFamily_A12 = 0x7D34B9F,
  CPUFamily_A13 = 0x462504D2,
  CPUFamily_A14 = 0x1B588BB3,
  CPUFamily_A15 = 0xDA33D83D,
  CPUFamily_A16 = 0x8765EDEA,
  CPUFamily_A17 = 0x2876F5B5,
};

/* 164 */
struct struct_krwCtx
{
  uint32_t flags;
  uint8_t gap4[168];
  uint32_t threadForKernelRead;
  uint8_t gap42[144];
  int xnuMajorVersion;
  uint8_t gap144[20];
  uint64_t someLargeNumber;
  uint8_t gap160[8];
  int int168;
  int gap16C[5];
  int pageSizeOrSomething;
  int gap16C2;
  uint64_t qword188;
  uint8_t gap190[136];
  uint64_t gap190u;
  uint8_t gap190_[56];
  int isRW;
  struct mach_timebase_info timebase;
  mach_port_t semaphore;
  pthread_mutex_t someMutex;
  uint32_t someInt1;
  uint32_t someInt2;
  uint64_t gap19100[16];
  pthread_mutex_t someMutex2;
  uint64_t gap191[695];
  uint32_t gap1909;
  uint32_t gap1910;
  uint32_t gap1911[2];
  uint32_t gap1913;
  uint32_t gap1914;
  uint32_t gap1915;
  uint32_t gap1916;
  uint64_t gap192[16];
  uint64_t machHeaderPlus0x8000;
  uint64_t gap19210;
  uint64_t gap19211;
  uint64_t slideMaybe;
  uint64_t gap1921[108];
  uint64_t qword1D48;
};
typedef struct struct_krwCtx struct_krwCtx;

/* 165 */
struct __attribute__((packed)) __attribute__((aligned(4))) struct_qword1D48
{
  _BYTE gap0[80];
  _QWORD qword50;
  _QWORD qword58;
  _QWORD qword60;
  _QWORD qword68;
  _DWORD dword70;
};
typedef struct __attribute__((packed)) __attribute__((aligned(4))) struct_qword1D48 struct_qword1D48;

/* 166 */
struct __attribute__((packed)) __attribute__((aligned(8))) struct_xnuMajorVersion
{
  _OWORD majorVersion;
  _OWORD oword10;
  _QWORD qword20;
};
typedef struct __attribute__((packed)) __attribute__((aligned(8))) struct_xnuMajorVersion struct_xnuMajorVersion;

/* 168 */
struct __attribute__((packed)) __attribute__((aligned(2))) struct_v83
{
  _BYTE gap0[48];
  _DWORD dword30;
  _BYTE gap34[4];
  _DWORD dword38;
  _BYTE gap3C[52];
  _OWORD xnuMajorVersion;
  _OWORD oword80;
  _QWORD qword90;
  _DWORD dword98;
  _BYTE gap9C[12];
  _QWORD qwordA8;
  _BYTE gapB0[81];
  _BYTE byte101;
};
typedef struct __attribute__((packed)) __attribute__((aligned(2))) struct_v83 struct_v83;

/* 169 */
struct __attribute__((packed)) __attribute__((aligned(8))) struct_a1
{
  _OWORD oword0;
  _OWORD oword10;
  _OWORD oword20;
  _OWORD oword30;
  _OWORD oword40;
  _OWORD oword50;
  _OWORD oword60;
  _OWORD xnuMajorVersion;
  _OWORD oword80;
  _OWORD oword90;
  _OWORD owordA0;
  _OWORD owordB0;
  _OWORD owordC0;
  _OWORD owordD0;
  _OWORD owordE0;
  _OWORD owordF0;
  _OWORD oword100;
  _OWORD oword110;
  _QWORD qword120;
};
typedef struct __attribute__((packed)) __attribute__((aligned(8))) struct_a1 struct_a1;

/* 173 */
enum krw_ctx_flags
{
  KRW_CTX_FLAG_CS_TXM = 0x20,
  KRW_CTX_FLAG_CS_PPL_MAYBE = 0x8,
};
